-- Insert dummy data for countries
INSERT INTO countries (name_ar, name_en, slug, description_ar, description_en, image_url, flag_url, currency, language, climate, study_cost_min, study_cost_max, living_cost_min, living_cost_max, popular_cities, visa_requirements_ar, visa_requirements_en, is_trending, client_id) VALUES
('كندا', 'Canada', 'canada', 'دولة متقدمة في أمريكا الشمالية تشتهر بجودة التعليم العالي والطبيعة الخلابة', 'A developed country in North America known for high-quality education and beautiful nature', 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce', 'https://flagcdn.com/w320/ca.png', 'CAD', 'الإنجليزية والفرنسية', 'معتدل إلى بارد', 15000, 35000, 12000, 20000, '["تورونتو", "فانكوفر", "مونتريال", "أوتاوا"]', 'تأشيرة دراسة مطلوبة', 'Study visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('أستراليا', 'Australia', 'australia', 'دولة متقدمة في أوقيانوسيا تتميز بجامعات عالمية ومناخ معتدل', 'A developed country in Oceania with world-class universities and moderate climate', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4', 'https://flagcdn.com/w320/au.png', 'AUD', 'الإنجليزية', 'معتدل إلى حار', 20000, 45000, 15000, 25000, '["سيدني", "ملبورن", "بريزبن", "أديلايد"]', 'تأشيرة طلابية مطلوبة', 'Student visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('ألمانيا', 'Germany', 'germany', 'دولة أوروبية رائدة في التعليم والتكنولوجيا مع رسوم دراسية منخفضة', 'A leading European country in education and technology with low tuition fees', 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b', 'https://flagcdn.com/w320/de.png', 'EUR', 'الألمانية', 'معتدل', 0, 3000, 8000, 12000, '["برلين", "ميونيخ", "هامبورغ", "كولونيا"]', 'تأشيرة دراسة مطلوبة للطلاب غير الأوروبيين', 'Study visa required for non-EU students', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('بريطانيا', 'United Kingdom', 'uk', 'موطن أعرق الجامعات في العالم مع تاريخ تعليمي عريق', 'Home to the world''s oldest universities with a rich educational heritage', 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad', 'https://flagcdn.com/w320/gb.png', 'GBP', 'الإنجليزية', 'معتدل ممطر', 25000, 50000, 12000, 18000, '["لندن", "أكسفورد", "كامبريدج", "إدنبرة"]', 'تأشيرة طلابية مطلوبة', 'Student visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('الولايات المتحدة', 'United States', 'usa', 'أقوى اقتصاد في العالم وموطن أفضل الجامعات والمعاهد البحثية', 'The world''s strongest economy and home to the best universities and research institutes', 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74', 'https://flagcdn.com/w320/us.png', 'USD', 'الإنجليزية', 'متنوع', 25000, 70000, 15000, 30000, '["نيويورك", "لوس أنجلوس", "شيكاغو", "بوسطن"]', 'تأشيرة F-1 للطلاب', 'F-1 student visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('فرنسا', 'France', 'france', 'دولة أوروبية عريقة تشتهر بالثقافة والفنون والتعليم المتميز', 'A historic European country famous for culture, arts, and excellent education', 'https://images.unsplash.com/photo-1431274172761-fca41d930114', 'https://flagcdn.com/w320/fr.png', 'EUR', 'الفرنسية', 'معتدل', 2000, 10000, 8000, 15000, '["باريس", "ليون", "مارسيليا", "تولوز"]', 'تأشيرة دراسة مطلوبة', 'Study visa required', false, (SELECT id FROM clients WHERE name = 'علي نصر الدين'));