-- Insert dummy data for countries
INSERT INTO countries (name_ar, name_en, slug, description_ar, description_en, image_url, flag_url, currency, language, climate, study_cost_min, study_cost_max, living_cost_min, living_cost_max, popular_cities, visa_requirements_ar, visa_requirements_en, is_trending, client_id) VALUES
('كندا', 'Canada', 'canada', 'دولة متقدمة في أمريكا الشمالية تشتهر بجودة التعليم العالي والطبيعة الخلابة', 'A developed country in North America known for high-quality education and beautiful nature', 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce', 'https://flagcdn.com/w320/ca.png', 'CAD', 'الإنجليزية والفرنسية', 'معتدل إلى بارد', 15000, 35000, 12000, 20000, '["تورونتو", "فانكوفر", "مونتريال", "أوتاوا"]', 'تأشيرة دراسة مطلوبة', 'Study visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('أستراليا', 'Australia', 'australia', 'دولة متقدمة في أوقيانوسيا تتميز بجامعات عالمية ومناخ معتدل', 'A developed country in Oceania with world-class universities and moderate climate', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4', 'https://flagcdn.com/w320/au.png', 'AUD', 'الإنجليزية', 'معتدل إلى حار', 20000, 45000, 15000, 25000, '["سيدني", "ملبورن", "بريزبن", "أديلايد"]', 'تأشيرة طلابية مطلوبة', 'Student visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('ألمانيا', 'Germany', 'germany', 'دولة أوروبية رائدة في التعليم والتكنولوجيا مع رسوم دراسية منخفضة', 'A leading European country in education and technology with low tuition fees', 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b', 'https://flagcdn.com/w320/de.png', 'EUR', 'الألمانية', 'معتدل', 0, 3000, 8000, 12000, '["برلين", "ميونيخ", "هامبورغ", "كولونيا"]', 'تأشيرة دراسة مطلوبة للطلاب غير الأوروبيين', 'Study visa required for non-EU students', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('بريطانيا', 'United Kingdom', 'uk', 'موطن أعرق الجامعات في العالم مع تاريخ تعليمي عريق', 'Home to the world\'s oldest universities with a rich educational heritage', 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad', 'https://flagcdn.com/w320/gb.png', 'GBP', 'الإنجليزية', 'معتدل ممطر', 25000, 50000, 12000, 18000, '["لندن", "أكسفورد", "كامبريدج", "إدنبرة"]', 'تأشيرة طلابية مطلوبة', 'Student visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('الولايات المتحدة', 'United States', 'usa', 'أقوى اقتصاد في العالم وموطن أفضل الجامعات والمعاهد البحثية', 'The world\'s strongest economy and home to the best universities and research institutes', 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74', 'https://flagcdn.com/w320/us.png', 'USD', 'الإنجليزية', 'متنوع', 25000, 70000, 15000, 30000, '["نيويورك", "لوس أنجلوس", "شيكاغو", "بوسطن"]', 'تأشيرة F-1 للطلاب', 'F-1 student visa required', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('فرنسا', 'France', 'france', 'دولة أوروبية عريقة تشتهر بالثقافة والفنون والتعليم المتميز', 'A historic European country famous for culture, arts, and excellent education', 'https://images.unsplash.com/photo-1431274172761-fca41d930114', 'https://flagcdn.com/w320/fr.png', 'EUR', 'الفرنسية', 'معتدل', 2000, 10000, 8000, 15000, '["باريس", "ليون", "مارسيليا", "تولوز"]', 'تأشيرة دراسة مطلوبة', 'Study visa required', false, (SELECT id FROM clients WHERE name = 'علي نصر الدين'));

-- Insert dummy data for universities
INSERT INTO universities (name_ar, name_en, slug, description_ar, description_en, country_id, city, website_url, logo_url, image_url, tuition_fee_min, tuition_fee_max, acceptance_rate, student_count, international_students_percentage, world_ranking, local_ranking, language_requirements, application_deadline, is_featured, client_id) VALUES
('جامعة تورونتو', 'University of Toronto', 'university-of-toronto', 'واحدة من أفضل الجامعات في كندا وأمريكا الشمالية', 'One of the top universities in Canada and North America', (SELECT id FROM countries WHERE slug = 'canada'), 'تورونتو', 'https://www.utoronto.ca', 'https://images.unsplash.com/photo-1562774053-701939374585', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a', 25000, 60000, 43.0, 97000, 25.0, 18, 1, 'IELTS 6.5 أو TOEFL 100', '2024-12-01', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('جامعة أكسفورد', 'University of Oxford', 'oxford-university', 'أقدم جامعة في العالم الناطق بالإنجليزية', 'The oldest university in the English-speaking world', (SELECT id FROM countries WHERE slug = 'uk'), 'أكسفورد', 'https://www.ox.ac.uk', 'https://images.unsplash.com/photo-1564981797816-1043664bf78d', 'https://images.unsplash.com/photo-1520637836862-4d197d17c50a', 35000, 55000, 17.5, 24000, 45.0, 2, 1, 'IELTS 7.0 أو TOEFL 110', '2024-10-15', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('معهد ماساتشوستس للتكنولوجيا', 'MIT', 'mit', 'واحد من أفضل المعاهد التقنية في العالم', 'One of the world\'s top technical institutes', (SELECT id FROM countries WHERE slug = 'usa'), 'بوسطن', 'https://www.mit.edu', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a', 'https://images.unsplash.com/photo-1562774053-701939374585', 55000, 75000, 6.7, 11000, 33.0, 1, 1, 'IELTS 7.0 أو TOEFL 90', '2024-01-01', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('الجامعة الوطنية الأسترالية', 'Australian National University', 'anu', 'الجامعة الرائدة في أستراليا للبحث والتعليم', 'Australia\'s leading university for research and education', (SELECT id FROM countries WHERE slug = 'australia'), 'كانبرا', 'https://www.anu.edu.au', 'https://images.unsplash.com/photo-1564981797816-1043664bf78d', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4', 30000, 45000, 35.0, 25000, 42.0, 27, 1, 'IELTS 6.5 أو TOEFL 80', '2024-11-30', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('جامعة ميونيخ التقنية', 'Technical University of Munich', 'tum', 'جامعة ألمانية رائدة في الهندسة والتكنولوجيا', 'A leading German university in engineering and technology', (SELECT id FROM countries WHERE slug = 'germany'), 'ميونيخ', 'https://www.tum.de', 'https://images.unsplash.com/photo-1562774053-701939374585', 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b', 0, 3000, 8.0, 45000, 30.0, 50, 2, 'IELTS 6.0 أو TestDaF', '2024-07-15', false, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('جامعة السوربون', 'Sorbonne University', 'sorbonne', 'جامعة فرنسية عريقة في قلب باريس', 'A prestigious French university in the heart of Paris', (SELECT id FROM countries WHERE slug = 'france'), 'باريس', 'https://www.sorbonne-universite.fr', 'https://images.unsplash.com/photo-1564981797816-1043664bf78d', 'https://images.unsplash.com/photo-1431274172761-fca41d930114', 2000, 10000, 32.0, 55000, 20.0, 72, 3, 'DELF B2 أو IELTS 6.0', '2024-05-31', false, (SELECT id FROM clients WHERE name = 'علي نصر الدين'));

-- Insert dummy data for programs
INSERT INTO programs (name_ar, name_en, slug, description_ar, description_en, university_id, country_id, degree_level, field_of_study, duration_years, duration_months, tuition_fee, language, requirements_ar, requirements_en, career_prospects_ar, career_prospects_en, start_date, application_deadline, is_featured, client_id) VALUES
('بكالوريوس علوم الحاسوب', 'Bachelor of Computer Science', 'computer-science-bachelor', 'برنامج شامل في علوم الحاسوب والبرمجة', 'Comprehensive program in computer science and programming', (SELECT id FROM universities WHERE slug = 'university-of-toronto'), (SELECT id FROM countries WHERE slug = 'canada'), 'بكالوريوس', 'علوم الحاسوب', 4, 48, 55000, 'الإنجليزية', 'شهادة ثانوية عامة بمعدل 85% على الأقل', 'High school diploma with at least 85% average', 'مطور برمجيات، مهندس أنظمة، محلل بيانات', 'Software developer, systems engineer, data analyst', '2024-09-01', '2024-05-01', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('ماجستير إدارة الأعمال', 'Master of Business Administration', 'mba-oxford', 'برنامج ماجستير متميز في إدارة الأعمال', 'Distinguished MBA program', (SELECT id FROM universities WHERE slug = 'oxford-university'), (SELECT id FROM countries WHERE slug = 'uk'), 'ماجستير', 'إدارة الأعمال', 1, 12, 75000, 'الإنجليزية', 'شهادة بكالوريوس + خبرة عملية 3 سنوات', 'Bachelor degree + 3 years work experience', 'مدير تنفيذي، استشاري إداري، رائد أعمال', 'Executive manager, management consultant, entrepreneur', '2024-09-01', '2024-03-31', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('دكتوراه في الهندسة', 'PhD in Engineering', 'phd-engineering-mit', 'برنامج دكتوراه متقدم في الهندسة', 'Advanced PhD program in engineering', (SELECT id FROM universities WHERE slug = 'mit'), (SELECT id FROM countries WHERE slug = 'usa'), 'دكتوراه', 'الهندسة', 5, 60, 65000, 'الإنجليزية', 'شهادة ماجستير في مجال ذي صلة', 'Master degree in related field', 'أستاذ جامعي، باحث، مهندس أول', 'University professor, researcher, senior engineer', '2024-08-15', '2024-12-15', true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('بكالوريوس الطب', 'Bachelor of Medicine', 'medicine-bachelor-anu', 'برنامج طبي متكامل', 'Comprehensive medical program', (SELECT id FROM universities WHERE slug = 'anu'), (SELECT id FROM countries WHERE slug = 'australia'), 'بكالوريوس', 'الطب', 6, 72, 70000, 'الإنجليزية', 'شهادة ثانوية علمية بمعدل عالي + اختبار قدرات', 'Science high school diploma with high grades + aptitude test', 'طبيب عام، اختصاصي، جراح', 'General practitioner, specialist, surgeon', '2024-02-01', '2024-10-31', false, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('ماجستير الهندسة الميكانيكية', 'Master of Mechanical Engineering', 'mechanical-engineering-tum', 'برنامج ماجستير متقدم في الهندسة الميكانيكية', 'Advanced master program in mechanical engineering', (SELECT id FROM universities WHERE slug = 'tum'), (SELECT id FROM countries WHERE slug = 'germany'), 'ماجستير', 'الهندسة الميكانيكية', 2, 24, 500, 'الألمانية', 'شهادة بكالوريوس في الهندسة', 'Bachelor degree in engineering', 'مهندس ميكانيكي، مصمم صناعي، باحث', 'Mechanical engineer, industrial designer, researcher', '2024-10-01', '2024-07-15', false, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('بكالوريوس الآداب', 'Bachelor of Arts', 'arts-bachelor-sorbonne', 'برنامج شامل في الآداب والعلوم الإنسانية', 'Comprehensive program in arts and humanities', (SELECT id FROM universities WHERE slug = 'sorbonne'), (SELECT id FROM countries WHERE slug = 'france'), 'بكالوريوس', 'الآداب', 3, 36, 8000, 'الفرنسية', 'شهادة ثانوية أدبية', 'Literary high school diploma', 'كاتب، مترجم، معلم، صحفي', 'Writer, translator, teacher, journalist', '2024-09-15', '2024-05-31', false, (SELECT id FROM clients WHERE name = 'علي نصر الدين'));

-- Insert dummy data for articles
INSERT INTO articles (title_ar, title_en, slug, excerpt_ar, excerpt_en, content_ar, content_en, category, author_name, author_avatar, featured_image, tags, reading_time, views_count, is_published, is_featured, client_id) VALUES
('دليلك الشامل للدراسة في كندا', 'Complete Guide to Studying in Canada', 'study-in-canada-guide', 'كل ما تحتاج معرفته عن الدراسة في كندا', 'Everything you need to know about studying in Canada', 'كندا واحدة من أفضل الوجهات الدراسية في العالم...', 'Canada is one of the best study destinations in the world...', 'دليل الدراسة', 'أحمد محمد', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce', '["كندا", "دراسة", "جامعات"]', 8, 1250, true, true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('أفضل التخصصات المطلوبة في سوق العمل', 'Most In-Demand Majors in Job Market', 'in-demand-majors-2024', 'تعرف على التخصصات الأكثر طلباً', 'Learn about the most sought-after specializations', 'مع التطور التكنولوجي السريع...', 'With rapid technological development...', 'سوق العمل', 'فاطمة أحمد', 'https://images.unsplash.com/photo-1494790108755-2616b612b69c', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f', '["وظائف", "تخصصات", "مستقبل"]', 6, 890, true, false, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('كيفية الحصول على منحة دراسية', 'How to Get a Scholarship', 'how-to-get-scholarship', 'خطوات عملية للحصول على منحة', 'Practical steps to get a scholarship', 'المنح الدراسية فرصة ذهبية...', 'Scholarships are a golden opportunity...', 'منح دراسية', 'محمد علي', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e', 'https://images.unsplash.com/photo-1523050854058-8df90110c9d1', '["منح", "تمويل", "دراسة"]', 10, 2100, true, true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('الحياة الطلابية في أستراليا', 'Student Life in Australia', 'student-life-australia', 'تجربة الطلاب العرب في أستراليا', 'Arab students experience in Australia', 'أستراليا وجهة دراسية مميزة...', 'Australia is a distinctive study destination...', 'حياة طلابية', 'ليلى حسن', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4', '["أستراليا", "طلاب", "تجربة"]', 7, 650, true, false, (SELECT id FROM clients WHERE name = 'علي نصر الدين'));

-- Insert dummy data for testimonials
INSERT INTO testimonials (name_ar, name_en, title_ar, title_en, content_ar, content_en, avatar_url, rating, is_featured, client_id) VALUES
('أحمد عبدالله', 'Ahmed Abdullah', 'طالب دكتوراه في جامعة تورونتو', 'PhD Student at University of Toronto', 'خدمة ممتازة ساعدتني في الوصول لحلمي. الفريق محترف ومتعاون جداً', 'Excellent service that helped me reach my dream. The team is very professional and cooperative', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', 5, true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('فاطمة محمد', 'Fatima Mohammed', 'طالبة ماجستير في جامعة أكسفورد', 'Master Student at Oxford University', 'بفضل مساعدتهم حصلت على قبول في جامعة أحلامي. شكراً لكم', 'Thanks to their help, I got accepted to my dream university. Thank you', 'https://images.unsplash.com/photo-1494790108755-2616b612b69c', 5, true, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('محمد الأحمد', 'Mohammed Al-Ahmed', 'طالب طب في الجامعة الوطنية الأسترالية', 'Medical Student at ANU', 'إجراءات سلسة ومتابعة مستمرة. أنصح بهم بشدة', 'Smooth procedures and continuous follow-up. I highly recommend them', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e', 5, false, (SELECT id FROM clients WHERE name = 'علي نصر الدين')),

('نورا سالم', 'Nora Salem', 'طالبة هندسة في ألمانيا', 'Engineering Student in Germany', 'خدمة استشارية متميزة وفريق يهتم بأدق التفاصيل', 'Distinguished consulting service and a team that cares about the smallest details', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80', 4, false, (SELECT id FROM clients WHERE name = 'علي نصر الدين'));