// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quzbycqecbxmcxagjcin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1emJ5Y3FlY2J4bWN4YWdqY2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjA5ODQsImV4cCI6MjA2OTkzNjk4NH0.rJ_QFIyo_axDgeLvdTzevY4f1HE2qR0OtHEXB9FsgBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});